#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if OS == UNIX_OS
#include <strings.h> // For the case insensitive strcasecmp() string comparison in Unix systems.
#endif

#include "cli_handler.h"

/** Returns whether or not the passed arg matches the compared expected argument. */
static bool is_arg(char *arg, const size_t argLength, char *expectedArg) {
    if (argLength != strlen(expectedArg)) {
        return false;
    }

#if OS == UNIX_OS
    return strcasecmp(arg, expectedArg) == 0;
#elif OS == WINDOWS_OS
    return _stricmp(arg, expectedArg) == 0;
#endif
}

/** Sets the flag of a matching argument in CLI, erroring if it was already set. */
static void set_flag(CliHandler *cli, bool *flagPtr) {
    if (*flagPtr) {
        cli->validArgs = false;
    } else {
        *flagPtr = true;
    }
}

/** Parses one argument into the CLI, setting an error if necessary.*/
static void cli_arg(char *arg, const int argIdx, CliHandler *cli) {
    const size_t length = strlen(arg);

    if (is_arg(arg, length, "--help") || is_arg(arg, length, "-help") || is_arg(arg, length, "-h")) {
        set_flag(cli, &cli->help);
    } else if (is_arg(arg, length, "--db-token")) {
        set_flag(cli, &cli->debugTokens);
    } else if (is_arg(arg, length, "--db-ast")) {
        set_flag(cli, &cli->debugAst);
    } else if (is_arg(arg, length, "--db-bytecode")) {
        set_flag(cli, &cli->debugBytecode);
    } else if (argIdx == 1) {
        cli->file = arg; // Take 2nd argument as file name.
    } else {
        cli->validArgs = false; // If it's not the 2nd argument, then it can't be the file name.
    }
}

/** Parses all the arguments in argv for the CLI. Starts at 2nd argument to skip the exe. */
static void parse_cli(const int argc, char **argv, CliHandler *cli) {
    for (int i = 1; i < argc; i++) {
        cli_arg(argv[i], i, cli);
    }
}

/** Creates a CLI (command line interface) handler, which is returned after parsing the args. */
CliHandler create_cli_handler(const int argc, char **argv) {
    CliHandler cli = {
        .validArgs = true, .file = NULL,
        .help = false, .debugTokens = false, .debugAst = false, .debugBytecode = false,
        .exitCode = 0, .manuallyExited = false
    };
    parse_cli(argc, argv, &cli);
    return cli; // Returns a copy, which still has all the flags set.
}

/** Prints the documentation of the CLI. */
void print_cli_help() {
    printf("Run file: zymux <file> [options]\n");
    printf("Run REPL: zymux [options]\n");
    printf("--------------------------------\n");
    printf("options:\n");
    printf("--help | -help | -h: show help menu.\n");
    printf("--db-token: print lexed tokens.\n");
    printf("--db-ast: print abstract syntax tree.\n");
    printf("--db-bytecode: print generated bytecode.\n");
}
