name: Zymux test flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools (Make and GCC)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run unit tests
        run: make unit-test || { echo "Unit tests failed" && exit 1; }

      - name: Run integration tests
        run: make integration-test || { echo "Integration tests failed" && exit 1; }
